[package]
name = "s3-clone"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.33"
env_logger = "0.11.8"
log = "0.4.27"
axum = "0.8.3"
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
